server {
  listen 8080;

  # Reporting endpoints
  add_header Reporting-Endpoints 'default="https://reportd.natwelch.com/reporting/subalpinedrift"' always;
  add_header Report-To '{"group":"default","max_age":10886400,"endpoints":[{"url":"https://reportd.natwelch.com/report/subalpinedrift"}]}' always;

  # Content Security Policy
  add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://unpkg.com; connect-src 'self' https://reportd.natwelch.com; img-src 'self'; style-src 'self' 'unsafe-inline'; report-to default;" always;

  # Cross-Origin policies
  add_header Cross-Origin-Opener-Policy 'same-origin; report-to="default"' always;

  location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }
}
